#!/bin/env -S ansible-playbook -i inventory
---
- name: manage junos host
  hosts: junos
  collections:
    - juniper.device
  connection: juniper.device.pyez
  gather_facts: false

  pre_tasks:

    - name: Fail if not junos
      ansible.builtin.fail:
      no_log: true
      when: ansible_network_os != "junipernetworks.junos.junos"

    - name: Bootstrap system for Ansible
      block:
        - name: retrieve facts from devices
          connection: juniper.device.pyez
          juniper.device.facts:
            savedir: "{{ playbook_dir }}"
      rescue:
        - name: enable netconf service
          connection: ansible.netcommon.network_cli
          junipernetworks.junos.junos_netconf:
        - name: retrieve facts from devices
          connection: juniper.device.pyez
          juniper.device.facts:
            savedir: "{{ playbook_dir }}"

  tasks:

#    - ansible.builtin.debug:
#        msg: "{{ ansible_facts }}"
#    - meta: end_play

    - ansible.builtin.include_tasks: "{{ include }}"
      loop_control:
        loop_var: include
      loop:
        - junos_system.yaml
        - junos_switch.yaml

  handlers:

    - name: commit config
      connection: ansible.netcommon.netconf
      junipernetworks.junos.junos_config:
        confirm_commit: true
        comment: "Updated by Ansible"

